version: "2.4"

services:
  selenium:
    container_name: selenium-test
    build: ${PWD}/docker
    volumes:
      - ./src:/code
    environment:
      - PYTHONUNBUFFERED=0
      - PYTHONPATH=/code/pom
  selenoid:
    container_name: selenoid
    image: "aerokube/selenoid"
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - ${PWD}/config/:/etc/selenoid/
      - "/var/run/docker.sock:/var/run/docker.sock"
  selenoid-ui:
    container_name: selenium-ui
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]
  chrome:
    container_name: chrome-vnc-99.0
    image: "selenoid/vnc_chrome:99.0"
    network_mode: bridge
    links:
      - selenoid
  allure:
    container_name: allure
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: NONE
      KEEP_HISTORY: 1
      KEEP_HISTORY_LATEST: 25
    ports:
      - "5050:5050"
    links:
      - selenoid
    volumes:
      - ${PWD}/allure-reports:/app/allure-reports
      - ${PWD}/allure-results:/app/allure-results
  allure-ui:
    container_name: allure-ui
    image: "frankescobar/allure-docker-service-ui"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    ports:
      - "5252:5252"
    links:
      - selenoid